// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace TSSLogParser.EFCore
{
    public partial class Datum
    {
        public string Data { get; set; }
        public decimal? EventId { get; set; }
        public decimal EventDataId { get; set; }
    }
}