// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace TSSLogParser.EFCore
{
    public partial class FlatEvent
    {
        public decimal EventId { get; set; }
        public decimal EventDataId { get; set; }
        public long? Binary { get; set; }
        public decimal SystemId { get; set; }
        public int? EventId1 { get; set; }
        public byte? Level { get; set; }
        public byte? Task { get; set; }
        public string Keywords { get; set; }
        public int? EventRecordId { get; set; }
        public string Channel { get; set; }
        public string Computer { get; set; }
        public string Security { get; set; }
        public string Name { get; set; }
        public DateTime? SystemTime { get; set; }
        public string Message { get; set; }
    }
}