// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace TSSLogParser.EFCore
{
    public partial class RegionalTotal
    {
        public string AppService { get; set; }
        public string LogName { get; set; }
        public string ProviderName { get; set; }
        public string TruncatedMessage { get; set; }
        public string LevelDisplayName { get; set; }
        public int? Id { get; set; }
        public string CountryCode { get; set; }
        public string Region { get; set; }
        public string AppCode { get; set; }
        public string InfraCode { get; set; }
        public int? MachineCount { get; set; }
        public int? MessageCount { get; set; }
        public string FullMessage { get; set; }
        public string MsftDocsSearch { get; set; }
        public string MsftDocsTopResult { get; set; }
        public string WebSearch { get; set; }
        public string WebTopResult { get; set; }
    }
}