// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace TSSLogParser.EFCore
{
    public partial class RegionalMachineCount
    {
        public string AppService { get; set; }
        public string LogName { get; set; }
        public string ProviderName { get; set; }
        public int? Id { get; set; }
        public string TruncatedMessage { get; set; }
        public string CountryCode { get; set; }
        public string Region { get; set; }
        public string InfraCode { get; set; }
        public int? MachineCount { get; set; }
    }
}