// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace TSSLogParser.EFCore
{
    public partial class RunSSISPkgXMLImportResult
    {
    }
}
