// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace TSSLogParser.EFCore
{
    public partial class TimeCreated
    {
        public DateTime? SystemTime { get; set; }
        public decimal? SystemId { get; set; }
    }
}