// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace TSSLogParser.EFCore
{
    public partial class TSSParserContext : DbContext
    {
        public TSSParserContext()
        {
        }

        public TSSParserContext(DbContextOptions<TSSParserContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Datum> Data { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventDatum> EventData { get; set; }
        public virtual DbSet<EventLog> EventLogs { get; set; }
        public virtual DbSet<EventLogsClean> EventLogsCleans { get; set; }
        public virtual DbSet<EventLogsFresh> EventLogsFreshes { get; set; }
        public virtual DbSet<FlatEvent> FlatEvents { get; set; }
        public virtual DbSet<GlobalMachineCount> GlobalMachineCounts { get; set; }
        public virtual DbSet<GlobalMessageCount> GlobalMessageCounts { get; set; }
        public virtual DbSet<GlobalTotal> GlobalTotals { get; set; }
        public virtual DbSet<MachineMetadatum> MachineMetadata { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<Recommendation> Recommendations { get; set; }
        public virtual DbSet<RegionalMachineCount> RegionalMachineCounts { get; set; }
        public virtual DbSet<RegionalMessageCount> RegionalMessageCounts { get; set; }
        public virtual DbSet<RegionalTotal> RegionalTotals { get; set; }
        public virtual DbSet<System> Systems { get; set; }
        public virtual DbSet<TimeCreated> TimeCreateds { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Datum>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.EventDataId)
                    .HasColumnType("numeric(20, 0)")
                    .HasColumnName("EventData_Id");

                entity.Property(e => e.EventId)
                    .HasColumnType("numeric(20, 0)")
                    .HasColumnName("Event_Id");
            });

            modelBuilder.Entity<Event>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("Event");

                entity.Property(e => e.EventId)
                    .HasColumnType("numeric(20, 0)")
                    .HasColumnName("Event_Id");
            });

            modelBuilder.Entity<EventDatum>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.EventDataId)
                    .HasColumnType("numeric(20, 0)")
                    .HasColumnName("EventData_Id");

                entity.Property(e => e.EventId)
                    .HasColumnType("numeric(20, 0)")
                    .HasColumnName("Event_Id");
            });

            modelBuilder.Entity<EventLog>(entity =>
            {
                entity.HasKey(e => new { e.RecordId, e.MachineName, e.LogName });

                entity.Property(e => e.MachineName).HasMaxLength(50);

                entity.Property(e => e.LogName).HasMaxLength(100);

                entity.Property(e => e.AppService).HasMaxLength(255);

                entity.Property(e => e.ContainerLog)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.LevelDisplayName).HasMaxLength(255);

                entity.Property(e => e.MsftDocsTopResult).HasMaxLength(255);

                entity.Property(e => e.ProviderName).HasMaxLength(255);

                entity.Property(e => e.WebTopResult).HasMaxLength(255);
            });

            modelBuilder.Entity<EventLogsClean>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("EventLogsClean");

                entity.Property(e => e.AppService).HasMaxLength(255);

                entity.Property(e => e.ContainerLog)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.LevelDisplayName).HasMaxLength(255);

                entity.Property(e => e.LogName)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.MachineName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.MsftDocsTopResult).HasMaxLength(255);

                entity.Property(e => e.ProviderName).HasMaxLength(255);

                entity.Property(e => e.WebTopResult).HasMaxLength(255);
            });

            modelBuilder.Entity<EventLogsFresh>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("EventLogsFresh");

                entity.Property(e => e.AppCode).HasMaxLength(3);

                entity.Property(e => e.AppService).HasMaxLength(255);

                entity.Property(e => e.ContainerLog)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.CountryCode).HasMaxLength(2);

                entity.Property(e => e.Domain).HasMaxLength(50);

                entity.Property(e => e.InfraCode).HasMaxLength(2);

                entity.Property(e => e.InstanceNum).HasMaxLength(2);

                entity.Property(e => e.LevelDisplayName).HasMaxLength(255);

                entity.Property(e => e.LogName)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.MachineName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.MachineType).HasMaxLength(3);

                entity.Property(e => e.MsftDocsTopResult).HasMaxLength(255);

                entity.Property(e => e.ProviderName).HasMaxLength(255);

                entity.Property(e => e.Region).HasMaxLength(3);

                entity.Property(e => e.WebTopResult).HasMaxLength(255);
            });

            modelBuilder.Entity<FlatEvent>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("FlatEvent");

                entity.Property(e => e.Channel).HasMaxLength(255);

                entity.Property(e => e.Computer).HasMaxLength(255);

                entity.Property(e => e.EventDataId)
                    .HasColumnType("numeric(20, 0)")
                    .HasColumnName("EventData_Id");

                entity.Property(e => e.EventId)
                    .HasColumnType("numeric(20, 0)")
                    .HasColumnName("Event_Id");

                entity.Property(e => e.EventId1).HasColumnName("EventID");

                entity.Property(e => e.EventRecordId).HasColumnName("EventRecordID");

                entity.Property(e => e.Keywords).HasMaxLength(255);

                entity.Property(e => e.Name).HasMaxLength(255);

                entity.Property(e => e.Security).HasMaxLength(255);

                entity.Property(e => e.SystemId)
                    .HasColumnType("numeric(20, 0)")
                    .HasColumnName("System_Id");

                entity.Property(e => e.SystemTime).HasColumnType("datetime");
            });

            modelBuilder.Entity<GlobalMachineCount>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("GlobalMachineCounts");

                entity.Property(e => e.LogName)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.ProviderName).HasMaxLength(255);
            });

            modelBuilder.Entity<GlobalMessageCount>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("GlobalMessageCounts");

                entity.Property(e => e.AppService).HasMaxLength(255);

                entity.Property(e => e.LevelDisplayName).HasMaxLength(255);

                entity.Property(e => e.LogName)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.MsftDocsTopResult).HasMaxLength(255);

                entity.Property(e => e.ProviderName).HasMaxLength(255);

                entity.Property(e => e.WebTopResult).HasMaxLength(255);
            });

            modelBuilder.Entity<GlobalTotal>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("GlobalTotals");

                entity.Property(e => e.AppService).HasMaxLength(255);

                entity.Property(e => e.LevelDisplayName).HasMaxLength(255);

                entity.Property(e => e.LogName)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.MsftDocsTopResult).HasMaxLength(255);

                entity.Property(e => e.ProviderName).HasMaxLength(255);

                entity.Property(e => e.WebTopResult).HasMaxLength(255);
            });

            modelBuilder.Entity<MachineMetadatum>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("MachineMetadata");

                entity.Property(e => e.AppCode).HasMaxLength(3);

                entity.Property(e => e.CountryCode).HasMaxLength(2);

                entity.Property(e => e.Domain).HasMaxLength(50);

                entity.Property(e => e.InfraCode).HasMaxLength(2);

                entity.Property(e => e.InstanceNum).HasMaxLength(2);

                entity.Property(e => e.MachineName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.MachineType).HasMaxLength(3);

                entity.Property(e => e.Region).HasMaxLength(3);
            });

            modelBuilder.Entity<Provider>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("Provider");

                entity.Property(e => e.Name).HasMaxLength(255);

                entity.Property(e => e.SystemId)
                    .HasColumnType("numeric(20, 0)")
                    .HasColumnName("System_Id");
            });

            modelBuilder.Entity<Recommendation>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("Recommendations");

                entity.Property(e => e.AppService).HasMaxLength(255);

                entity.Property(e => e.LevelDisplayName).HasMaxLength(255);

                entity.Property(e => e.LogName)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.MsftDocsTopResult).HasMaxLength(255);

                entity.Property(e => e.ProviderName).HasMaxLength(255);

                entity.Property(e => e.WebTopResult).HasMaxLength(255);
            });

            modelBuilder.Entity<RegionalMachineCount>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("RegionalMachineCounts");

                entity.Property(e => e.AppService).HasMaxLength(255);

                entity.Property(e => e.CountryCode).HasMaxLength(2);

                entity.Property(e => e.InfraCode).HasMaxLength(2);

                entity.Property(e => e.LogName)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.ProviderName).HasMaxLength(255);

                entity.Property(e => e.Region).HasMaxLength(3);
            });

            modelBuilder.Entity<RegionalMessageCount>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("RegionalMessageCounts");

                entity.Property(e => e.AppCode).HasMaxLength(3);

                entity.Property(e => e.AppService).HasMaxLength(255);

                entity.Property(e => e.CountryCode).HasMaxLength(2);

                entity.Property(e => e.Domain).HasMaxLength(50);

                entity.Property(e => e.InfraCode).HasMaxLength(2);

                entity.Property(e => e.InstanceNum).HasMaxLength(2);

                entity.Property(e => e.LevelDisplayName).HasMaxLength(255);

                entity.Property(e => e.LogName)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.MachineName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.MachineType).HasMaxLength(3);

                entity.Property(e => e.MsftDocsTopResult).HasMaxLength(255);

                entity.Property(e => e.ProviderName).HasMaxLength(255);

                entity.Property(e => e.Region).HasMaxLength(3);

                entity.Property(e => e.WebTopResult).HasMaxLength(255);
            });

            modelBuilder.Entity<RegionalTotal>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("RegionalTotals");

                entity.Property(e => e.AppCode).HasMaxLength(3);

                entity.Property(e => e.AppService).HasMaxLength(255);

                entity.Property(e => e.CountryCode).HasMaxLength(2);

                entity.Property(e => e.InfraCode).HasMaxLength(2);

                entity.Property(e => e.LevelDisplayName).HasMaxLength(255);

                entity.Property(e => e.LogName)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.MsftDocsTopResult).HasMaxLength(255);

                entity.Property(e => e.ProviderName).HasMaxLength(255);

                entity.Property(e => e.Region).HasMaxLength(3);

                entity.Property(e => e.WebTopResult).HasMaxLength(255);
            });

            modelBuilder.Entity<System>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("System");

                entity.Property(e => e.Channel).HasMaxLength(255);

                entity.Property(e => e.Computer).HasMaxLength(255);

                entity.Property(e => e.EventId).HasColumnName("EventID");

                entity.Property(e => e.EventId1)
                    .HasColumnType("numeric(20, 0)")
                    .HasColumnName("Event_Id");

                entity.Property(e => e.EventRecordId).HasColumnName("EventRecordID");

                entity.Property(e => e.Keywords).HasMaxLength(255);

                entity.Property(e => e.Security).HasMaxLength(255);

                entity.Property(e => e.SystemId)
                    .HasColumnType("numeric(20, 0)")
                    .HasColumnName("System_Id");
            });

            modelBuilder.Entity<TimeCreated>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("TimeCreated");

                entity.Property(e => e.SystemId)
                    .HasColumnType("numeric(20, 0)")
                    .HasColumnName("System_Id");

                entity.Property(e => e.SystemTime).HasColumnType("datetime");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}